### ISSUE TITLE
FitGirl Repacks are clean

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/Warez#11]
* [FitGirl Repacks background installer (fgpack.exe) contains "MITRE ATT&CK" and "Dridex configuration" - Collecting Banking/E-Mail Information](https://www.hybrid-analysis.com/sample/c1c71e0cd1c1cc427bce265f7bdb7d5a0ce399064c9f4e410d42e05b92412203)
* [Reddit Thread](https://old.reddit.com/r/Piracy/comments/eesyjs/fitgirl_repacks_background_installer_fgpackexe/)

**Comment by maximousblk** [comment]
This is probably because some hackers modified one of the repacks, someone reported it and now the original repack being similar is getting false positives.

Also
> [Bitdefender Theta is 100% Machine Learning powered](https://blog.virustotal.com/2019/10/virustotal-bitdefender-theta.html) - VirusTotal Blog

So, it is possible to get false positives, because static definition based antiviruses check for the exact behavior, but AI based antiviruses look for *similar* behavior

**Comment by CHEF-KOCH** [comment]
Fake packages and manipulated files within original and legititame packages are not really a FitGirl problem, it's a common problem.

What repackers should always do, sadly they do not do it is to prove checksums to verify that the package are not altered BEFORE you even down/install something. FitGirl has a checksum verification which gets triggered AFTER you install/downloaded the package, but it's pointless since an attacker could manipulate the entire package and let the verification always pass. It also only verifies the game files, but not the package itself.

**Comment by maximousblk** [comment]
So, this is sorted?

**Comment by maximousblk** [comment]
close this.
