### ISSUE TITLE
Suggestion to Gab Social inclusion in this list.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [CHEF-KOCH/Warez#7]
Don’t really see the advantage of pushing that one, instead of the actual Mastodon other instances.
Especially due to the sheer degrative nature of their services, foundators and users, making their domains to be generally blacklisted from the rest of the Fediverse.
Also, moreover, doesn’t they put free features of Mastodon behind pay-walls?
I would suggest the LaQuadratureDuNet mamot.fr instance, or privacytools.io one social.privacytools.io.

**Comment by CHEF-KOCH** [comment]
You're more than welcome to submit a pull request.

**Comment by maximousblk** [comment]
close this.
