### ISSUE TITLE
Terrible advice from /r/piracy

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/Warez#9]
Those clows at /r/piracy, you can't make this up... (_not all of them, there are some good guys over there but in this case..._)

Source:
https://www.reddit.com/r/Piracy/wiki/vetting_game_downloads

Thread:
https://www.reddit.com/r/Piracy/comments/e7pgtr/guide_how_to_verify_that_a_game_download_is_safe/

Screenshot:
![dwdwwdwdwdwd](https://user-images.githubusercontent.com/727123/70520493-8b269680-1b35-11ea-9881-7d0fbe797d41.png)

I don't know which clown this "guidance" wrote but this guy/girl seriously is not involved into any scene.

`It is in the nature of antiviruses to flag pirated software/cracks as viruses/trojans/riskware, etc, so your game download will inevitably be flagged as such by your antivirus, even if it's safe to run`

No, it's not and you do not have any clue what you're talking about here, there are factors to consider like how the files are been packed, if the AV can look behind it and if or if not some injection methods are been used. There are game cracks which are perfectly FUD (fully undetectable) and clean (stealth). Flagging things is not an indicator for riskware, it's often a false positive as a result of how the AV scans/handles things, your configuration and how the overall "crack" was done.

`Doing a proper search for your game.`

Hell, no! Proper search is called "research". But this isn't possible in any warez related topic because you can't "ask" scener directly without exposing them and leak the information to the web, that's why we have xrel-dot-to and other "indexer" (_scene release databases_). Which is basically the only way to check if a release is "real" or not.

`Fitgirl repacks are repackaged from original scene releases. Her releases are very popular and are safe to install...`

Oh boy, Fitgirl is not a girl, maybe actually read the FAQ and the docs. 

`However, her repacks are extremely compressed and can take hours to install, even on a beefy system. Keep this in mind before opting to download from her site. The point of repacks such as these is to offer people with very slow or data-capped internet a chance to download games in a timely manner.`

That is depending what compression algo was used and the ratio. Fitgirl over time optimized it. It's also depending on the game size as well as other factors.

`The checksum value you copied is the CRC32 checksum of the original scene release. `

No one should use MD/CRC/SHA1 anymore, collusion attacks are already discovered and right now you should use SHA256 (or other "state-of-the-art" secure hash algorithm).

`How to calculate the CRC32 checksum of your .iso file`

If you don't know how to calculate hashes please do not download some pirated software. You also do not need any tools to get the hashes, Windows, Linux and MacOS can do this without tools. There is a example given [here](https://www.tenforums.com/tutorials/78681-add-file-hash-context-menu-windows-8-10-a.html). 

`If your download is a set of rar files, use this method`

Just open the .rar or the one with 1 in the name and that's it, Winrar will find the rest during the extraction process, Winrar checks the folder for other files automatically, and if no others are been detected it even asks you for the missing parts 2,3,4, etc. 

I drop the 🎤 at this point, I'm done with it.

**Comment by maximousblk** [comment]
Maybe properly rewrite this guide and add it to the guides section
